name: Deploy

on:
  push:
    branches:
      - master

jobs:
  export:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./site

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3        
        with:
          node-version: 16.x                 
      - run: npm install
      - run: npm run export

  clear-s3:
    name: prepare s3 to deploy new version static site
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./site

    steps:  
      - name: Configure AWS Credentials
      - uses: actions/checkout@v3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_ID }}
          aws-region: us-east-1

    - name: Remove old files
      run: |
        aws s3 rm --recursive s3://matheus-oliveira-andrade.com

  deploy:
    name: send new version to s3
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./site

    steps:  
      - name: Configure AWS Credentials
      - uses: actions/checkout@v3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_ID }}
          aws-region: us-east-1

    - name: Copy new files
      run: |
        aws s3 sync .\out\ s3://matheus-oliveira-andrade.com